"""
inkbox.imessage — iMessage types.
"""

from inkbox.imessage.types import (
    IMessage,
    IMessageAssignment,
    IMessageAssignmentStatus,
    IMessageContactRule,
    IMessageConversation,
    IMessageConversationSummary,
    IMessageDeliveryStatus,
    IMessageGroupCreationStatus,
    IMessageNumber,
    IMessageNumberStatus,
    IMessageNumberType,
    IMessageMarkReadResult,
    IMessageMessageReaction,
    IMessageMediaItem,
    IMessageMediaUpload,
    IMessageReaction,
    IMessageReactionType,
    IMessageRecipient,
    IMessageRuleAction,
    IMessageRuleMatchType,
    IMessageSendStyle,
    IMessageService,
    IMessageTriageNumber,
)

__all__ = [
    "IMessage",
    "IMessageAssignment",
    "IMessageAssignmentStatus",
    "IMessageContactRule",
    "IMessageConversation",
    "IMessageConversationSummary",
    "IMessageDeliveryStatus",
    "IMessageGroupCreationStatus",
    "IMessageNumber",
    "IMessageNumberStatus",
    "IMessageNumberType",
    "IMessageMarkReadResult",
    "IMessageMessageReaction",
    "IMessageMediaItem",
    "IMessageMediaUpload",
    "IMessageReaction",
    "IMessageReactionType",
    "IMessageRecipient",
    "IMessageRuleAction",
    "IMessageRuleMatchType",
    "IMessageSendStyle",
    "IMessageService",
    "IMessageTriageNumber",
]
