"""Contact types and resource options."""

from inkbox.contacts.resources.correspondence import ContactCorrespondenceOptions
from inkbox.contacts.types import (
    CallCorrespondenceItem,
    Contact,
    ContactAccess,
    ContactCorrespondence,
    ContactCreationSource,
    ContactFact,
    ContactFactCitation,
    ContactFactCitationAvailability,
    ContactFactCitationDetail,
    ContactFactOrigin,
    ContactImportStatus,
    ContactNameSource,
    ContactReviewStatus,
    CorrespondenceAttachmentMetadata,
    CorrespondenceChannel,
    CorrespondenceChannelResult,
    CorrespondenceChannelStatus,
    CorrespondenceContentMode,
    CorrespondenceDirection,
    CorrespondenceItem,
    CorrespondenceMediaMetadata,
    CorrespondenceOrder,
    CorrespondenceTranscriptEntry,
    CorrespondenceTranscriptMarker,
    CorrespondenceTranscriptMode,
    EmailCorrespondenceItem,
    IMessageCorrespondenceItem,
    SmsCorrespondenceItem,
)

__all__ = [
    "CallCorrespondenceItem",
    "Contact",
    "ContactAccess",
    "ContactCorrespondence",
    "ContactCorrespondenceOptions",
    "ContactCreationSource",
    "ContactFact",
    "ContactFactCitation",
    "ContactFactCitationAvailability",
    "ContactFactCitationDetail",
    "ContactFactOrigin",
    "ContactImportStatus",
    "ContactNameSource",
    "ContactReviewStatus",
    "CorrespondenceAttachmentMetadata",
    "CorrespondenceChannel",
    "CorrespondenceChannelResult",
    "CorrespondenceChannelStatus",
    "CorrespondenceContentMode",
    "CorrespondenceDirection",
    "CorrespondenceItem",
    "CorrespondenceMediaMetadata",
    "CorrespondenceOrder",
    "CorrespondenceTranscriptEntry",
    "CorrespondenceTranscriptMarker",
    "CorrespondenceTranscriptMode",
    "EmailCorrespondenceItem",
    "IMessageCorrespondenceItem",
    "SmsCorrespondenceItem",
]
