"""Contact types and resource options."""

from inkbox.contacts.resources.correspondence import ContactCorrespondenceOptions
from inkbox.contacts.resources.permissions import ContactPermissions, ContactPermissionsResource
from inkbox.contacts.resources.communication_policy import (
    ContactAddressPermission, ContactAddressUpdate, ContactDecision,
    ContactCommunicationPolicy, ContactCommunicationPreview, ContactCommunicationPolicyPage,
    ContactVisibilityDecisions, ContactIdentityVisibilityDecisions, ContactVisibilityPolicy, ContactVisibilityResult,
    ContactPermissionSummary, ContactPermissionVisibility, ContactPermissionEffective, ContactPermissionEntry, ContactPermissionPage, IdentifierPermission,
)
from inkbox.contacts.types import (
    CallCorrespondenceItem,
    Contact,
    ContactCreatePermissions,
    ContactAccess,
    ContactBulkDeleteResult,
    ContactBulkDeleteResultItem,
    ContactBulkDeleteStatus,
    ContactCorrespondence,
    ContactCreationSource,
    ContactFact,
    ContactFactCitation,
    ContactFactCitationAvailability,
    ContactFactCitationDetail,
    ContactFactDeleteResult,
    ContactFactKind,
    ContactFactOrigin,
    ContactImportStatus,
    ContactImportResult,
    ContactImportResultItem,
    ContactMemorySummary,
    ContactNameSource,
    ContactReviewStatus,
    ContactVCardExportResult,
    CorrespondenceAttachmentMetadata,
    CorrespondenceChannel,
    CorrespondenceChannelResult,
    CorrespondenceChannelStatus,
    CorrespondenceContentMode,
    CorrespondenceDirection,
    CorrespondenceItem,
    CorrespondenceMediaMetadata,
    CorrespondenceOrder,
    CorrespondenceTranscriptEntry,
    CorrespondenceTranscriptMarker,
    CorrespondenceTranscriptMode,
    EmailCorrespondenceItem,
    IMessageCorrespondenceItem,
    SmsCorrespondenceItem,
)

__all__ = [
    "ContactPermissions", "ContactPermissionsResource",
    "ContactAddressPermission", "ContactAddressUpdate", "ContactDecision",
    "ContactCommunicationPolicy", "ContactCommunicationPreview", "ContactCommunicationPolicyPage",
    "ContactVisibilityDecisions", "ContactIdentityVisibilityDecisions", "ContactVisibilityPolicy", "ContactVisibilityResult",
    "ContactPermissionSummary", "ContactPermissionVisibility", "ContactPermissionEffective", "ContactPermissionEntry", "ContactPermissionPage", "IdentifierPermission",
    "CallCorrespondenceItem",
    "Contact",
    "ContactCreatePermissions",
    "ContactAccess",
    "ContactBulkDeleteResult",
    "ContactBulkDeleteResultItem",
    "ContactBulkDeleteStatus",
    "ContactCorrespondence",
    "ContactCorrespondenceOptions",
    "ContactCreationSource",
    "ContactFact",
    "ContactFactCitation",
    "ContactFactCitationAvailability",
    "ContactFactCitationDetail",
    "ContactFactDeleteResult",
    "ContactFactKind",
    "ContactFactOrigin",
    "ContactImportStatus",
    "ContactImportResult",
    "ContactImportResultItem",
    "ContactMemorySummary",
    "ContactNameSource",
    "ContactReviewStatus",
    "ContactVCardExportResult",
    "CorrespondenceAttachmentMetadata",
    "CorrespondenceChannel",
    "CorrespondenceChannelResult",
    "CorrespondenceChannelStatus",
    "CorrespondenceContentMode",
    "CorrespondenceDirection",
    "CorrespondenceItem",
    "CorrespondenceMediaMetadata",
    "CorrespondenceOrder",
    "CorrespondenceTranscriptEntry",
    "CorrespondenceTranscriptMarker",
    "CorrespondenceTranscriptMode",
    "EmailCorrespondenceItem",
    "IMessageCorrespondenceItem",
    "SmsCorrespondenceItem",
]
