"""A2A inbox and standard-protocol client."""

from inkbox.a2a.client import A2AClient, A2AProtocolError
from inkbox.a2a.types import (
    A2ACard,
    A2ACaller,
    A2AContactRule,
    A2AContext,
    A2AContextPage,
    A2AMessage,
    A2AReplyIntent,
    A2AResolvedTarget,
    A2ARuleAction,
    A2ARuleDirection,
    A2ASendResult,
    A2ASettings,
    A2ASkill,
    A2ATask,
    A2ATaskPage,
    A2ATaskState,
    A2ATransition,
    A2AWireMessage,
    A2AWireTask,
    A2AWireTaskPage,
    A2AWireTaskState,
)

__all__ = [
    "A2ACard",
    "A2ACaller",
    "A2AClient",
    "A2AContactRule",
    "A2AContext",
    "A2AContextPage",
    "A2AMessage",
    "A2AProtocolError",
    "A2AReplyIntent",
    "A2AResolvedTarget",
    "A2ARuleAction",
    "A2ARuleDirection",
    "A2ASendResult",
    "A2ASettings",
    "A2ASkill",
    "A2ATask",
    "A2ATaskPage",
    "A2ATaskState",
    "A2ATransition",
    "A2AWireMessage",
    "A2AWireTask",
    "A2AWireTaskPage",
    "A2AWireTaskState",
]
