"""
inkbox — Python SDK for the Inkbox APIs.
"""

from inkbox.client import Inkbox
from inkbox.agent_identity import AgentIdentity
from inkbox.credentials import Credentials

# Exceptions (canonical source)
from inkbox.exceptions import (
    DuplicateContactRuleError,
    InkboxAPIError,
    InkboxError,
    InkboxVaultKeyError,
    RecipientBlockedError,
    RedundantContactAccessGrantError,
)

# Mail types
from inkbox.mail.types import (
    ContactRuleStatus,
    Domain,
    FilterMode,
    FilterModeChangeNotice,
    ForwardMode,
    MailContactRule,
    MailIdentityContactRule,
    MailRuleAction,
    MailRuleMatchType,
    Mailbox,
    Message,
    MessageDetail,
    MessageDirection,
    ReplyAllRecipients,
    SendingDomainStatus,
    Thread,
    ThreadDetail,
    ThreadFolder,
)

# Phone types
from inkbox.phone.types import (
    CallOrigin,
    IncomingCallAction,
    IncomingCallActionConfig,
    PhoneCall,
    PhoneCallWithRateLimit,
    PhoneContactRule,
    PhoneIdentityContactRule,
    PhoneNumber,
    PhoneRuleAction,
    PhoneRuleMatchType,
    PhoneTranscript,
    RateLimitInfo,
    SmsDeliveryStatus,
    SmsOptIn,
    SmsOptInSource,
    SmsOptInStatus,
    SmsStatus,
    TextConversationSummary,
    TextConversationUpdateResult,
    TextMediaItem,
    TextMessage,
    TextMessageRecipient,
    TextMessageOrigin,
)

# iMessage types
from inkbox.imessage.types import (
    IMessage,
    IMessageAssignment,
    IMessageAssignmentStatus,
    IMessageContactRule,
    IMessageConversation,
    IMessageConversationSummary,
    IMessageDeliveryStatus,
    IMessageMarkReadResult,
    IMessageMediaItem,
    IMessageMessageReaction,
    IMessageMediaUpload,
    IMessageReaction,
    IMessageReactionType,
    IMessageRecipient,
    IMessageRuleAction,
    IMessageRuleMatchType,
    IMessageSendStyle,
    IMessageService,
    IMessageTriageNumber,
)

# Identity types
from inkbox.identities.types import (
    AgentIdentitySummary,
    IdentityAccess,
    IdentityMailboxCreateOptions,
    IdentityMailbox,
    IdentityPhoneNumberCreateOptions,
    IdentityPhoneNumber,
    IdentityTunnelCreateOptions,
)

# Contacts types
from inkbox.contacts.types import (
    Contact,
    ContactAccess,
    ContactAddress,
    ContactCustomField,
    ContactDate,
    ContactEmail,
    ContactImportResult,
    ContactImportResultItem,
    ContactPhone,
    ContactWebsite,
)

# Notes types
from inkbox.notes.types import Note, NoteAccess

# Vault types
from inkbox.vault.types import (
    AccessRule,
    APIKeyPayload,
    DecryptedVaultSecret,
    KeyPairPayload,
    LoginPayload,
    OtherPayload,
    SSHKeyPayload,
    VaultInfo,
    VaultInitializeResult,
    VaultKey,
    VaultKeyType,
    VaultSecret,
    VaultSecretDetail,
    VaultSecretType,
)
from inkbox.vault.totp import (
    TOTPAlgorithm,
    TOTPCode,
    TOTPConfig,
    generate_totp,
    parse_totp_uri,
)
from inkbox.vault.crypto import (
    VaultKeyMaterial,
    generate_org_encryption_key,
    generate_recovery_code,
    generate_vault_key_material,
)

# Agent signup types
from inkbox.agent_signup.types import (
    AgentSignupResponse,
    AgentSignupVerifyResponse,
    AgentSignupResendResponse,
    AgentSignupStatusResponse,
    SignupRestrictions,
)

# Whoami types and named auth_subtype constants
from inkbox.whoami.types import (
    AUTH_SUBTYPE_API_KEY_ADMIN_SCOPED,
    AUTH_SUBTYPE_API_KEY_AGENT_SCOPED_CLAIMED,
    AUTH_SUBTYPE_API_KEY_AGENT_SCOPED_UNCLAIMED,
    WhoamiApiKeyResponse,
    WhoamiJwtResponse,
    WhoamiResponse,
)

# Tunnels types + exceptions
from inkbox.tunnels.types import (
    SignedCert,
    TLSMode,
    Tunnel,
    TunnelStatus,
)
from inkbox.tunnels.exceptions import (
    TunnelCSRStateConflict,
    TunnelError,
    TunnelNameInvalid,
    TunnelNotProvisioned,
    TunnelRemoved,
    TunnelStateConflict,
    TunnelSupersededError,
    TunnelTLSModeMismatch,
)
from inkbox.tunnels._validation import (
    normalize_agent_handle,
    validate_agent_handle,
    validate_tunnel_name,
)
from inkbox.identities.exceptions import (
    BlockingNamespace,
    HandleUnavailableError,
)

# Signing key + webhook verification
from inkbox.signing_keys import SigningKey, SigningKeyStatus, verify_webhook

# Receiver-side webhook payload types
from inkbox.webhooks import (
    CallDirectionWire,
    CallEndedWebhookData,
    CallEndedWebhookPayload,
    CallLifecycleWebhookEventType,
    CallOriginWire,
    CallStatusWire,
    HangupReasonWire,
    MailContactBucket,
    MailWebhookData,
    MailWebhookEventType,
    MailWebhookMessage,
    MailWebhookPayload,
    MessageDirectionWire,
    MessageStatus,
    PhoneIncomingCallWebhookPayload,
    RateLimitInfoWire,
    SmsDeliveryStatusWire,
    TextDirectionWire,
    TextMediaItemWire,
    TextMessageRecipientWire,
    TextMessageOriginWire,
    TextTypeWire,
    IMessageDeliveryStatusWire,
    IMessageDirectionWire,
    IMessageMediaItemWire,
    IMessageMessageReactionWire,
    IMessageReactionTypeWire,
    IMessageRecipientWire,
    IMessageSendStyleWire,
    IMessageServiceWire,
    IMessageTypeWire,
    IMessageWebhookData,
    IMessageWebhookEventType,
    IMessageWebhookMessage,
    IMessageWebhookPayload,
    IMessageWebhookReaction,
    TextWebhookData,
    TextWebhookEventType,
    TextWebhookMessage,
    TextWebhookPayload,
    WebhookAgentIdentity,
    WebhookContact,
    WebhookContextBlockWire,
    WebhookContextCallItemWire,
    WebhookContextMailItemWire,
    WebhookContextModeWire,
    WebhookContextScopeWire,
    WebhookContextSkipReasonWire,
    WebhookContextTextChannelWire,
    WebhookContextTextItemWire,
    WebhookContextWire,
    WebhookCallTranscript,
    WebhookMailAgentIdentity,
    WebhookMailContact,
    WebhookPhoneCall,
    WebhookTranscriptEntryWire,
)

# Webhook subscription resource (CRUD)
from inkbox.webhook_subscriptions import (
    WebhookContextClassConfig,
    WebhookContextConfig,
    WebhookContextCountConfig,
    WebhookContextWindowConfig,
    WebhookSubscription,
    WebhookSubscriptionCreateResponse,
    WebhookSubscriptionsResource,
    WebhookSubscriptionStatus,
)

# Webhook delivery log + replay
from inkbox.webhook_deliveries import (
    WebhookDelivery,
    WebhookDeliveriesResource,
)

# API keys
from inkbox.api_keys.types import ApiKey, ApiKeyStatus, CreatedApiKey

__all__ = [
    # Entry points
    "Inkbox",
    "AgentIdentity",
    "Credentials",
    # Exceptions
    "InkboxError",
    "InkboxAPIError",
    "InkboxVaultKeyError",
    "DuplicateContactRuleError",
    "RecipientBlockedError",
    "RedundantContactAccessGrantError",
    # Mail types
    "ContactRuleStatus",
    "Domain",
    "FilterMode",
    "FilterModeChangeNotice",
    "ForwardMode",
    "MailContactRule",
    "MailIdentityContactRule",
    "MailRuleAction",
    "MailRuleMatchType",
    "Mailbox",
    "Message",
    "MessageDetail",
    "MessageDirection",
    "ReplyAllRecipients",
    "SendingDomainStatus",
    "Thread",
    "ThreadDetail",
    "ThreadFolder",
    # Phone types
    "CallOrigin",
    "IncomingCallAction",
    "IncomingCallActionConfig",
    "PhoneCall",
    "PhoneCallWithRateLimit",
    "PhoneContactRule",
    "PhoneIdentityContactRule",
    "PhoneNumber",
    "PhoneRuleAction",
    "PhoneRuleMatchType",
    "PhoneTranscript",
    "RateLimitInfo",
    "SmsDeliveryStatus",
    "SmsOptIn",
    "SmsOptInSource",
    "SmsOptInStatus",
    "SmsStatus",
    "TextConversationSummary",
    "TextConversationUpdateResult",
    "TextMediaItem",
    "TextMessage",
    "TextMessageRecipient",
    "TextMessageOrigin",
    # iMessage types
    "IMessage",
    "IMessageAssignment",
    "IMessageAssignmentStatus",
    "IMessageContactRule",
    "IMessageConversation",
    "IMessageConversationSummary",
    "IMessageDeliveryStatus",
    "IMessageMarkReadResult",
    "IMessageMediaItem",
    "IMessageMessageReaction",
    "IMessageMediaUpload",
    "IMessageReaction",
    "IMessageReactionType",
    "IMessageRecipient",
    "IMessageRuleAction",
    "IMessageRuleMatchType",
    "IMessageSendStyle",
    "IMessageService",
    "IMessageTriageNumber",
    # Identity types
    "AgentIdentitySummary",
    "IdentityAccess",
    "IdentityMailboxCreateOptions",
    "IdentityMailbox",
    "IdentityPhoneNumberCreateOptions",
    "IdentityPhoneNumber",
    "IdentityTunnelCreateOptions",
    # Contacts types
    "Contact",
    "ContactAccess",
    "ContactAddress",
    "ContactCustomField",
    "ContactDate",
    "ContactEmail",
    "ContactImportResult",
    "ContactImportResultItem",
    "ContactPhone",
    "ContactWebsite",
    # Notes types
    "Note",
    "NoteAccess",
    # Vault types
    "AccessRule",
    "VaultSecretType",
    "VaultKeyType",
    "VaultInfo",
    "VaultKey",
    "VaultSecret",
    "VaultSecretDetail",
    "DecryptedVaultSecret",
    "VaultInitializeResult",
    "LoginPayload",
    "SSHKeyPayload",
    "APIKeyPayload",
    "KeyPairPayload",
    "OtherPayload",
    "VaultKeyMaterial",
    "generate_org_encryption_key",
    "generate_vault_key_material",
    "generate_recovery_code",
    # TOTP
    "TOTPAlgorithm",
    "TOTPCode",
    "TOTPConfig",
    "generate_totp",
    "parse_totp_uri",
    # Agent signup types
    "AgentSignupResponse",
    "AgentSignupVerifyResponse",
    "AgentSignupResendResponse",
    "AgentSignupStatusResponse",
    "SignupRestrictions",
    # Whoami types + auth_subtype constants
    "AUTH_SUBTYPE_API_KEY_ADMIN_SCOPED",
    "AUTH_SUBTYPE_API_KEY_AGENT_SCOPED_CLAIMED",
    "AUTH_SUBTYPE_API_KEY_AGENT_SCOPED_UNCLAIMED",
    "WhoamiApiKeyResponse",
    "WhoamiJwtResponse",
    "WhoamiResponse",
    # Tunnels
    "SignedCert",
    "TLSMode",
    "Tunnel",
    "TunnelStatus",
    "TunnelCSRStateConflict",
    "TunnelError",
    "TunnelNameInvalid",
    "TunnelNotProvisioned",
    "TunnelRemoved",
    "TunnelStateConflict",
    "TunnelSupersededError",
    "TunnelTLSModeMismatch",
    "normalize_agent_handle",
    "validate_agent_handle",
    "validate_tunnel_name",
    # Identity exceptions
    "BlockingNamespace",
    "HandleUnavailableError",
    # Signing key + webhook verification
    "SigningKey",
    "SigningKeyStatus",
    "verify_webhook",
    # Receiver-side webhook payload types
    "CallDirectionWire",
    "CallEndedWebhookData",
    "CallEndedWebhookPayload",
    "CallLifecycleWebhookEventType",
    "CallOriginWire",
    "CallStatusWire",
    "HangupReasonWire",
    "MailContactBucket",
    "MailWebhookData",
    "MailWebhookEventType",
    "MailWebhookMessage",
    "MailWebhookPayload",
    "MessageDirectionWire",
    "MessageStatus",
    "PhoneIncomingCallWebhookPayload",
    "RateLimitInfoWire",
    "SmsDeliveryStatusWire",
    "TextDirectionWire",
    "TextMediaItemWire",
    "TextMessageRecipientWire",
    "TextMessageOriginWire",
    "TextTypeWire",
    "IMessageDeliveryStatusWire",
    "IMessageDirectionWire",
    "IMessageMediaItemWire",
    "IMessageMessageReactionWire",
    "IMessageReactionTypeWire",
    "IMessageRecipientWire",
    "IMessageSendStyleWire",
    "IMessageServiceWire",
    "IMessageTypeWire",
    "IMessageWebhookData",
    "IMessageWebhookEventType",
    "IMessageWebhookMessage",
    "IMessageWebhookPayload",
    "IMessageWebhookReaction",
    "TextWebhookData",
    "TextWebhookEventType",
    "TextWebhookMessage",
    "TextWebhookPayload",
    "WebhookAgentIdentity",
    "WebhookContact",
    "WebhookContextBlockWire",
    "WebhookContextCallItemWire",
    "WebhookContextMailItemWire",
    "WebhookContextModeWire",
    "WebhookContextScopeWire",
    "WebhookContextSkipReasonWire",
    "WebhookContextTextChannelWire",
    "WebhookContextTextItemWire",
    "WebhookContextWire",
    "WebhookCallTranscript",
    "WebhookMailAgentIdentity",
    "WebhookMailContact",
    "WebhookPhoneCall",
    "WebhookTranscriptEntryWire",
    # Webhook subscriptions
    "WebhookContextClassConfig",
    "WebhookContextConfig",
    "WebhookContextCountConfig",
    "WebhookContextWindowConfig",
    "WebhookSubscription",
    "WebhookSubscriptionCreateResponse",
    "WebhookSubscriptionsResource",
    "WebhookSubscriptionStatus",
    # Webhook deliveries
    "WebhookDelivery",
    "WebhookDeliveriesResource",
    # API keys
    "ApiKey",
    "ApiKeyStatus",
    "CreatedApiKey",
]
